### ISSUE TITLE
KBL-5 主界面可用引擎数易引起误解，应设为不可选

### ISSUE THREAD

**Issue by Jayson0626** [JayHeng/nxp-sec-boot-ui#12]
我觉得最好显示最大可用引擎数，1050的就显示1个，而且是灰色不可下拉的，1060的直接显示2个且灰色不可下拉。
![9-1](https://user-images.githubusercontent.com/44720384/49878571-dd6da280-fe62-11e8-9126-8a8d10f291a3.png)
![9-2](https://user-images.githubusercontent.com/44720384/49878579-e2caed00-fe62-11e8-9d59-77a0233cdf26.png)

**Comment by JayHeng** [comment]
在下一版修复
