### ISSUE TITLE
KBL-6 BEE加密参数配置界面未激活的控件（主要是Choice）应全部设为灰色

### ISSUE THREAD

**Issue by Jayson0626** [JayHeng/nxp-sec-boot-ui#13]
选择了引擎0，引擎1的那边是不是可以都灰色不可选呢？
![10-1](https://user-images.githubusercontent.com/44720384/49878735-46551a80-fe63-11e8-9cbd-19832c23c473.png)

**Comment by JayHeng** [comment]
Choice控件background颜色设置不生效，正在研究

**Comment by JayHeng** [comment]
使用 控件.Enable( False)方法即可解决问题
