### ISSUE TITLE
KBL-10 配置页面里任何非激活的控件（主要是Choice）均应设为不可选

### ISSUE THREAD

**Issue by Jayson0626** [JayHeng/nxp-sec-boot-ui#17]
配置boot device的时候，右边“Nor operation 1”在没有开启的情况下可以显示灰色不可选择的状态。
![13-1](https://user-images.githubusercontent.com/44720384/49939636-5e3aa600-ff18-11e8-824b-7e628dcb201b.png)

**Comment by JayHeng** [comment]
使用 控件.Enable( False)方法即可解决问题
