### ISSUE TITLE
KBL-11 使用非默认签名配置后重新打开工具，无法直接进入flashloader

### ISSUE THREAD

**Issue by Jayson0626** [JayHeng/nxp-sec-boot-ui#18]
使用HAB签名的时候默认是2048，签名后的flashloader默认放在一个路径，不关闭软件的情况下，默认调用2048生成的证书，但是当第一次使用的是1024或3072或4096时，不关闭工具的时候默认生成的就是第一次使用的长度。关闭并重新打开工具，此时再连接flashloader的时候默认使用的是2048的证书，并且无法进入flashloader！！！

**Comment by JayHeng** [comment]
软件整体配置保留功能已经添加，因此这个问题随之解决
