### ISSUE TITLE
当PC上有多个COM口时，UART在one-step模式下自动连接出错

### ISSUE THREAD

**Issue by relliktei** [JayHeng/nxp-sec-boot-ui#22]
我在试用这个软件，但是出现下边的错误，不知道怎么解决
![booterror](https://user-images.githubusercontent.com/41564775/50258542-1dbcba00-043b-11e9-95e2-3cda28d3d5ee.png)
我找到flashloader.srec文件了，但是用什么工具更新呢？

**Comment by Jayson0626** [comment]
> 我在试用这个软件，但是出现下边的错误，不知道怎么解决
> ![booterror](https://user-images.githubusercontent.com/41564775/50258542-1dbcba00-043b-11e9-95e2-3cda28d3d5ee.png)
> 我找到flashloader.srec文件了，但是用什么工具更新呢？

建议在master模式下单步连接，具体操作为：“Tool”->"Option"->"Master Mode",取消勾选“One-Step”，在进入BOOT ROM后，COM Port 应该为默认的COM3,此时_**务必**_重新选择一下com口，这是软件自身缺陷，下一版本将会修复此问题。

**Comment by JayHeng** [comment]
今天会release v0.15.0，新版本会修复该问题
