### ISSUE TITLE
EXT-4 可以放几个野火的版本的例程吗？

### ISSUE THREAD

**Issue by relliktei** [JayHeng/nxp-sec-boot-ui#35]
可以放几个修改好的野火的版本的例程吗？
我自己照着使用说明修改野火的例程，下载后led灯不亮，也不知道是成功还是修改的代码有问题

**Comment by JayHeng** [comment]
可以挂上Jlink halt住core查看PC值来确认是否Boot成功

**Comment by JayHeng** [comment]
使用nxpSecBoot下载完成之后可以在Boot Device Memory页面点击'View bootable image'按钮来查看下载到外存里数据

**Comment by JayHeng** [comment]
v1.0.0版本\nxp-sec-boot-ui\apps目录下已经放了野火全系列RT1052开发板（核心、Mini、Pro）的LED demo
