### ISSUE TITLE
KBL-32 在弹出无法发现USB的情况下复位板子可以直接view image

### ISSUE THREAD

**Issue by Jayson0626** [JayHeng/nxp-sec-boot-ui#46]
下载image后如果直接硬件复位boot image，下次在想连接板子的时候需要先点击reset device，此时会弹出无法找到USB端口的提示，这时候再连接板子后就可以在不下载image的情况下直接执行view image操作，从而出现不想要的结果。

**Comment by JayHeng** [comment]
与KBL-29同一问题
