### ISSUE TITLE
请问可以支持mdk的afx格式吗

### ISSUE THREAD

**Issue by byteman** [JayHeng/nxp-sec-boot-ui#6]
请问可以把mdk的afx格式支持上吗？现在我们都是用的mdk来开发的项目

**Comment by JayHeng** [comment]
目前只测试过IAR的.out(elf)以及标准的.s19文件，mdk的afx有可能是支持的，但是软件里设置了不识别.afx后缀的文件，你可以将.afx直接改成.elf后缀试一下看能否直接用。
下周我会把MDK输出文件的支持加进去

**Comment by byteman** [comment]
非常期待，谢谢

**Comment by JayHeng** [comment]
常见的五种image格式（.elf/.axf/.s19/.hex/.bin）已全部支持。
