### ISSUE TITLE
能否加一个读取flash中数据并保存为文件的功能

### ISSUE THREAD

**Issue by byteman** [JayHeng/nxp-sec-boot-ui#7]
是这样的，我再调试文件系统的时候，发现读取出来的内容和我写入的内容不一样，但是我又不知道到底是我写入的驱动的问题，还是读取部分的问题，所以想通过您这个软件来直接读取我写入的部分的内容保存问一个文件，然后计算我原本写入文件和读取出的文件的md5码，来判断到底是我写入还是读取部分驱动的问题，谢谢

**Comment by JayHeng** [comment]
其实软件有回读Flash内容并格式化显示的功能，在实现回读的时候其实在软件目录下临时保存了flash数据文件，但完成显示之后删除了flash数据文件。

你提的这个功能我这一周会加上。

**Comment by byteman** [comment]
感谢感谢，我现在是临时读取出来，然后拷贝您界面上的显示到一个文本文件，然后写了一个小工具，分析文本文件中的数据部分，再转成一个bin文件，如果有了您这个功能后，就能简化很多了.而且在读取比较大的数据的时候，软件界面会卡住，希望能优化一下

**Comment by JayHeng** [comment]
保存文件功能已添加
