### ISSUE TITLE
KBL-2 关于通用编程器功能的3点建议

### ISSUE THREAD

**Issue by Jayson0626** [JayHeng/nxp-sec-boot-ui#9]
1.通用编程器，start address从0开始，实际物理地址为0x60000000开始，或许可以将起始地址改为Offset start address，或者其他的方式以方便理解 
2.是不是可以再添加一个fill操作（再添加一个输入fill数据的入口），这样可以方便快速写入，write只能浏览文件才能写入想要的数据，有点麻烦。
3.NFCB标识的颜色刺眼，可以换种颜色！ 
![fcb](https://user-images.githubusercontent.com/44720384/49877535-9088cc80-fe60-11e8-8b64-8385ba91c661.png)

**Comment by JayHeng** [comment]
1. start address如果小于0x6000_0000则是offset address，如果大于0x6000_0000则是绝对地址，这是软件的设计。
2. fill操作不是通用编程器的必备，暂不考虑添加。
3. NFCB的颜色会重新调整。

**Comment by JayHeng** [comment]
item2暂未添加，其余已修复
